### ISSUE TITLE
cli not support formating output via commandline for all modules - example jsonrpc

### ISSUE THREAD

**Issue by khorsmann** [kamailio/kamcli#13]
### Issue description

Try to run jsonrpc commands for not yet implemented commands like dns subsets.
Want to output them as json via -F or --output-format param. Global set is yaml.
Greping around in the code, that variable/object oformat isnt in jsonrpc cmd file which seems to be filled with that options.

### Try to overwrite output format with CLI options

```
 grep outformat /etc/kamcli/kamcli.ini
; outformat - how RPC result is printed, can be: json or yaml
outformat=yaml
```

```
kamcli --output-format json jsonrpc dns.view
kamcli -F json jsonrpc dns.view


id: 1138
jsonrpc: '2.0'
result:
- expires: 2664
  last_used: 345
  name: _sip._tcp.whateverhere.primary.fancy.example.local
  negative_entry: 'no'
  permanent: 'no'
  records:
  - rr_expires: 2664
    rr_idx: 0
    rr_name: s-ecp-607.edns.somewhere.example
    rr_permanent: 'no'
    rr_port: 5060
    rr_priority: 10
    rr_weight: 0
  - rr_expires: 2664
    rr_idx: 1
    rr_name: h2-ecp-607.edns.somewhere.example
    rr_permanent: 'no'
    rr_port: 5060
    rr_priority: 20
    rr_weight: 0
  - rr_expires: 2664
    rr_idx: 2
    rr_name: d-ecp-607.edns.somewhere.example
    rr_permanent: 'no'
    rr_port: 5060
    rr_priority: 30
    rr_weight: 0
  reference_counter: 1
  size_bytes: 304
  type: SRV

```
### Change globale Output format

```
 grep outformat /etc/kamcli/kamcli.ini
; outformat - how RPC result is printed, can be: json or yaml
outformat=json
```

```
kamcli jsonrpc dns.view

{
    "jsonrpc": "2.0",
    "result": [
        {
            "name": "_sip._tcp.whateverhere.primary.fancy.example.local",
            "type": "SRV",
            "size_bytes": 304,
            "reference_counter": 1,
            "permanent": "no",
            "expires": 2557,
            "last_used": 452,
            "negative_entry": "no",
            "records": [
                {
                    "rr_idx": 0,
                    "rr_name": "s-ecp-607.edns.somewhere.example",
                    "rr_port": 5060,
                    "rr_priority": 10,
                    "rr_weight": 0,
                    "rr_permanent": "no",
                    "rr_expires": 2557
                },
                {
                    "rr_idx": 1,
                    "rr_name": "h2-ecp-607.edns.somewhere.example",
                    "rr_port": 5060,
                    "rr_priority": 20,
                    "rr_weight": 0,
                    "rr_permanent": "no",
                    "rr_expires": 2557
                },
                {
                    "rr_idx": 2,
                    "rr_name": "d-ecp-607.edns.somewhere.example",
                    "rr_port": 5060,
                    "rr_priority": 30,
                    "rr_weight": 0,
                    "rr_permanent": "no",
                    "rr_expires": 2557
                }
            ]
        },

```
